# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Truststore Inspector Tests

on:
  push:
    branches: [ main, fix_unit_tests ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "[*]Unit tests started"
      - name: Run tests with pytest
        run: python3 -m pytest -o log_cli=True
